# Generated by Django 5.2 on 2025-08-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
    ]
