# Generated by Django 5.2 on 2025-09-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0002_remove_contactus_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
