# Generated by Django 5.2 on 2025-05-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0002_usersubscription_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
