# Generated by Django 5.2 on 2025-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0003_remove_usersubscription_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='plan_expiring_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='renews_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
