# Generated by Django 5.2 on 2025-09-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0003_billinghistory_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinghistory',
            name='currency',
        ),
    ]
