# Generated by Django 5.2 on 2025-05-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0004_alter_usersubscription_plan_expiring_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='duration',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='current_plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='basic', max_length=10),
        ),
    ]
