# Generated by Django 5.2 on 2025-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0005_usersubscription_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='total_members',
            field=models.IntegerField(default=1),
        ),
    ]
