# Generated by Django 5.2 on 2025-05-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0007_billinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='invoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
