# Generated by Django 5.2 on 2025-05-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0008_billinghistory_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='pricing',
            new_name='original_price',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
