# Generated by Django 5.2 on 2025-05-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0010_billinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
