# Generated by Django 5.2 on 2025-05-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0012_apikey_apilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='monthly_credits',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='apikey',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
