# Generated by Django 5.2 on 2025-05-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0013_apikey_monthly_credits_apikey_plan_alter_apikey_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AddField(
            model_name='apikey',
            name='credits_remaining',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='apikey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
