# Generated by Django 5.2 on 2025-05-15 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0014_alter_apikey_options_apikey_credits_remaining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('message', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appln.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='APIKeyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='basic', max_length=20)),
                ('active_keys', models.JSONField(default=list)),
                ('revoked_keys', models.JSONField(default=list)),
                ('keys_remaining', models.IntegerField(default=0)),
                ('monthly_credits', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appln.userdata')),
            ],
            options={
                'verbose_name': 'API Key Manager',
            },
        ),
        migrations.AlterField(
            model_name='apilog',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='appln.apikeymanager'),
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
