# Generated by Django 5.2 on 2025-05-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0015_apiaccessrequest_apikeymanager_alter_apilog_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeymanager',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apikeymanager',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
