# Generated by Django 5.2 on 2025-05-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0017_alter_apikeymanager_revoked_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikeymanager',
            old_name='keys_remaining',
            new_name='credits_remaining',
        ),
    ]
