# Generated by Django 5.2 on 2025-05-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0018_rename_keys_remaining_apikeymanager_credits_remaining'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikeymanager',
            options={'verbose_name': 'API Key Manager', 'verbose_name_plural': 'API Key Managers'},
        ),
        migrations.RemoveField(
            model_name='apikeymanager',
            name='credits_remaining',
        ),
        migrations.AlterField(
            model_name='apikeymanager',
            name='active_keys',
            field=models.JSONField(default=list, help_text="List of active API keys: [{'key': 'abc', 'created_at': '...'}]"),
        ),
        migrations.AlterField(
            model_name='apikeymanager',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic (10 credits/month)'), ('pro', 'Pro (50 credits/month)'), ('enterprise', 'Enterprise (Unlimited)')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='apikeymanager',
            name='revoked_keys',
            field=models.JSONField(default=list, help_text="Revoked key history: [{'key': 'abc', 'revoked_at': '...', 'reason': '...'}]"),
        ),
        migrations.AlterField(
            model_name='apikeymanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key_manager', to='appln.userdata'),
        ),
    ]
