# Generated by Django 5.2 on 2025-05-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0019_alter_apikeymanager_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeymanager',
            name='credits_remaining',
            field=models.IntegerField(default=0, help_text='monthly_credits - usage_count'),
        ),
        migrations.AlterField(
            model_name='apikeymanager',
            name='active_keys',
            field=models.JSONField(default=list, help_text="List of active API keys, e.g. ['asfrbrrrnrnrrdaas']"),
        ),
        migrations.AlterField(
            model_name='apikeymanager',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, all keys disabled globally'),
        ),
        migrations.AlterField(
            model_name='apikeymanager',
            name='monthly_credits',
            field=models.IntegerField(default=10, help_text='Credits allocated per month based on plan'),
        ),
        migrations.AlterField(
            model_name='apikeymanager',
            name='revoked_keys',
            field=models.JSONField(default=list, help_text='Audit history of revoked keys with reason and date'),
        ),
        migrations.AlterField(
            model_name='apikeymanager',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Number of credits used this month'),
        ),
    ]
