# Generated by Django 5.2 on 2025-05-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0020_apikeymanager_credits_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeymanager',
            name='active_keys',
            field=models.CharField(help_text="List of active API keys, e.g. ['asfrbrrrnrnrrdaas']", max_length=50),
        ),
    ]
