# Generated by Django 5.2 on 2025-06-06 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0022_userdesignhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('credits_used', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appln.userdata')),
            ],
        ),
    ]
