# Generated by Django 5.2 on 2025-07-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0023_creditusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccessrequest',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
